// <auto-generated />
using System;
using InstallmentsModule.DAL.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InstallmentsModule.DAL.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230427150105_editMaximamLeanthTo50")]
    partial class editMaximamLeanthTo50
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("InstallmentsModule")
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("InstallmentsModule.DML.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedDatetime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastUpdateByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("LastUpdateDatetime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RefId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CreatedDatetime");

                    b.HasIndex("LastUpdateByUserId");

                    b.HasIndex("LastUpdateDatetime");

                    b.ToTable("Accounts", "InstallmentsModule");
                });

            modelBuilder.Entity("InstallmentsModule.DML.Entities.PaymentPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountRefId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BillId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BillTypeId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedDatetime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("Datetime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastUpdateByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("LastUpdateDatetime")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("varbinary(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPaiedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalRemainingAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AccountRefId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CreatedDatetime");

                    b.HasIndex("Datetime");

                    b.HasIndex("LastUpdateByUserId");

                    b.HasIndex("LastUpdateDatetime");

                    b.HasIndex("BillId", "BillTypeId")
                        .IsUnique()
                        .HasFilter("BillId IS NOT NULL and BillTypeId IS NOT NULL");

                    b.ToTable("PaymentPlan", "InstallmentsModule");
                });

            modelBuilder.Entity("InstallmentsModule.DML.Entities.PaymentPlanDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("HeaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PaiedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("PaiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("PaymentPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("RemainingAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("PaymentPlanId");

                    b.ToTable("PaymentPlanDetails", "InstallmentsModule");
                });

            modelBuilder.Entity("InstallmentsModule.DML.Entities.PaymentPlanDetails", b =>
                {
                    b.HasOne("InstallmentsModule.DML.Entities.PaymentPlan", null)
                        .WithMany("PaymentPlanDetails")
                        .HasForeignKey("PaymentPlanId");
                });

            modelBuilder.Entity("InstallmentsModule.DML.Entities.PaymentPlan", b =>
                {
                    b.Navigation("PaymentPlanDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
